# Generated by Django 5.0.1 on 2024-01-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0002_remove_event_date_event_end_event_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end",
        ),
    ]
